FROM visionaccelerator.azurecr.io/edge_base/amd64/python:3.7-slim-buster

RUN apt update && apt upgrade -y

RUN mkdir /models && chmod 777 -R /models

WORKDIR /app

COPY requirements.txt ./
RUN python3 -m pip install --upgrade pip setuptools wheel urllib3
RUN python3 -m pip install -r requirements.txt

RUN apt clean -y && apt autoremove -y

COPY . .

CMD [ "python3", "-u", "./main.py" ]